### ISSUE TITLE
Treinamento de Git

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#1]
Ensinar os conhecimentos básicos, para alguns membros, de git.

**Comment by nicaloribeiro** [comment]
**Links úteis** :  
- [Guia prático](https://rogerdudler.github.io/git-guide/index.pt_BR.html)  
- [Lista de comandos úteis](https://gist.github.com/leocomelli/2545add34e4fec21ec16)

**Comment by nicaloribeiro** [comment]
* Um treinamento presencial, para os que possuem dificuldades, tentará ser aplicado na próxima sprint.
