### ISSUE TITLE
Refatorar página de ajuda

### ISSUE THREAD

**Issue by lgpinheiro94** [fga-eps-mds/2019.2-Questmark#105]
# **Descrição**
 A página de ajuda precisa ser refatorada, afim de inserir uma instrução para que o usuário possa compreender de que modo ele pode inserir o questionário em sua página.

# **Objetivos**
O objetivo dessa issue é inserir uma instrução da página de ajuda, para que o usuário entenda de que modo ele pode inserir o questionário em sua página. Colocando essa informação de maneira elegante e responsiva, buscando que se adeque ao design e seus padrões. 

 # **Tasks**
 - [x] colocar como o usuário inserir o questionário na sua página;
 - [x] revisar possíveis erros ortográficos;
 - [x] revisar o código.

# **Comentários**
Qualquer dúvida pertinente a issue comentar abaixo.

**Comment by lgpinheiro94** [comment]
Todas as tasks foram cumpridas com sucesso.

**Comment by lgpinheiro94** [comment]
Gostaria de ter a opnião de vocês a respeito de mudarmos as cores da página de Ajuda, com a finalidade de as cores estarem mais semelhantes as das outras páginas, o que acham ? gostaria de trocar o "roxo" por "azul" que usamos nas outras páginas do Questmark, qual a opnião de vocês a respeito disso ? Aguardo um feedback e por favor deem uma revisa na página de Ajuda para qualquer futura correção da página.

**Comment by nicaloribeiro** [comment]
@DanilloGS @lucaslop @Gustavo-Nogueira @Miguelisdemir

**Comment by lucaslop** [comment]
Issue concluida #114
