### ISSUE TITLE
Isolar a API

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#106]
# **Descrição**
Para a reutilização e reaproveitamento de código do projeto Questmark Deve-se isolar parte da API  e tornar independente do projeto. as endpoints de converter Markdown para HTML, para ser reutilizável em outros projetos/códigos

# **Objetivos**

- Isolar a API de forma que torne independente e reutilizável

 # **Tasks**

- [x] Deve tornar acessível o (s) endpoint(s) da conversão de markdown para html
- [x] Testar manualmente usando postman ou similar

# **Comentários**

**Comment by Gustavo-Nogueira** [comment]
@lucaslop então deve ser criada uma no API com o código que faz o parse de _Markdown_ para HMTL ? Ou apenas adicionar uma rota que trata o parse dentro da API do Questmark? 
Lembrando que o código do WMD se encontra na parte de _frontend_, ou seja, o código de parse tem que ser passado para o _backend_.

**Comment by lucaslop** [comment]
@Gustavo-Nogueira Pode isolar a parte dos endpoints de conversão do markdown para html, porque atualmente, esta parte é dependente do Questmark. Ou seja, funciona só dentro do escopo do projeto. Ou criar novas endpoints separadas só com um 'post' para receber o markdown e um 'get' para retornar a saída em html. Em relação as funções do wmd. Basta importa no arquivo desses endpoints.

**Comment by Gustavo-Nogueira** [comment]
Teste de envio de requisições utilizando o _postman_.
![](https://user-images.githubusercontent.com/36088551/68733872-e0af6800-05b6-11ea-832c-6301a63b8392.png)

**Comment by DanilloGS** [comment]
A API foi isolada cumprindo todas as tasks propostas na issue. O PR #113 foi aceito e o merge foi feito, portanto a mesma foi finalizada
