### ISSUE TITLE
Realização de testes

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#107]
# **Descrição**
- Alguns testes relacionados as novas funcionalidades da plataforma Questmark devem ser feitos, ainda tem funcionalidades antigas que também precisam dos testes finalizados.

# **Objetivos**
- Finalizar os teste de endpoint e os unitários das rotas relacionadas aos formulários e aos usuários.

 # **Tasks**
 - [x] Testes nas novas rotas de usuários.
 - [x] Testes na rota de autenticar usuário.
 - [x] Testes nas novas rotas de formulários.
 - [x]  Criptografia.
 - [x] Recuperar senha.
 - [x] Teste do CSV
 - [x] Teste de autenticação 
# **Comentários**
Qualquer comentário pertinente a issue comentar abaixo.

**Comment by Miguelisdemir** [comment]
![comentando foto issue](https://user-images.githubusercontent.com/19369266/68539186-700e0e80-035e-11ea-8ff0-cddfc7793aa0.jpg)

Até 10/11 foi realizado mais de 58% de testes, sendo eles unitários e de integração . no teste das routes, foi abordado o seguinte método para testes: Testar os endpoints e posteriormente as funções (de callbacks)  e os middlewares separadamente para facilitar o processo de testes

**Comment by lucaslop** [comment]
Na data 11/11, foi realizado 24 testes em 7 suits  e timeout de 3.047s. Com Aprovação em todos ![image](https://user-images.githubusercontent.com/38164895/68539233-ead72980-035e-11ea-81d4-e600857a7f12.png)

**Comment by lucaslop** [comment]
O Máximo de cobertura alcançado foi de quase 60% da aplicação. Lembrando que, dividimos  em testes unitários e de integração nas rotas, para facilitar os testes.

![image](https://user-images.githubusercontent.com/38164895/68727427-29f5bc80-05a3-11ea-8faa-474d9bf25487.png)

**Comment by DanilloGS** [comment]
O PR #111 foi aceito finalizando então a issue atual.
