### ISSUE TITLE
Limpar código

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#116]
# **Descrição**
- Com a chegada da reta final do desenvolvimento do projeto, deve-se tornar o código da aplicação o mais limpo possível para o lançamento da versão final. 

# **Objetivos**
- Retirar linhas de códigos redundantes como comentários e console.log( ) que foram utilizadas para Debug durante o desenvolvimento. 

 # **Tasks**
 - [x] Retirar console.log( ). 
 - [x] Retirar comentários.
 - [x] Converter funções antigas do JS para arrow function. 

# **Comentários**
- Qualquer dúvida comentar abaixo.

**Comment by nicaloribeiro** [comment]
Foram encontrados alguns erros. Uma solução está sendo trabalhada.

**Comment by DanilloGS** [comment]
@nicaloribeiro a possível origem do erro deve ser as Arrow functions. Apesar de o WMD ser um código em Java Script o mesmo é bastante antigo(2010), pré arrow functions (2015). Deve está ocorrendo algum tipo de incompatibilidade.

**Comment by nicaloribeiro** [comment]
> @nicaloribeiro a possível origem do erro deve ser as Arrow functions. Apesar de o WMD ser um código em Java Script o mesmo é bastante antigo(2010), pré arrow functions (2015). Deve está ocorrendo algum tipo de incompatibilidade.

Por via das dúvidas, algumas 'functions()' foram mantidas ao invés de todas serem trocadas por arrow functions.
Um outro problema que estava acontecendo, que foi identificado e consertado, foram erros na sintaxe do EJS pós formatação do texto (ex :  Correto : "<%-" ; Erro:  "<% -").

**Comment by lucaslop** [comment]
Issue concluida #126
