### ISSUE TITLE
Botão para a home

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#117]
# **Descrição**
Na tela de **login** e **cadastro** , se o usuário não decidir logar, não há nenhum botão que redirecione para a tela inicial. Em vista disso, criar um botão para a tela home

# **Objetivos**
Criar um botão no simbolo (QM) que redirecione o usuário para a tela inicial

 # **Tasks**
- [x] Ao clicar no simbolo (QM) o usuário deve ser redirecionado para a tela inicial 

# **Comentários**
Qualquer dúvida, comentar abaixo

**Comment by DanilloGS** [comment]
Issue será finalizada assim que o pr #125 for aceito. Os desafios propostos foram concluídos

**Comment by lucaslop** [comment]
Eu e o @DanilloGS Corrigimos alguns erros simples. Porém, podem atrapalhar uma boa experiencia de usuário

**Comment by lucaslop** [comment]
Concluido #125
