### ISSUE TITLE
Criar overlay de deletar

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#118]
# **Descrição**
- Adicionar um overlay quando solicitado para apagar um questionário, assim como overlay de compartilhar um link.

# **Objetivos**
- Adicionar um overlay com a mesma identidade visual do overlay de compartilhamento, retirando o alert que está sendo utilizado até o momento.

 # **Tasks**
 - [x] Overlay com mesma identidade visual do de compartilhamento 

# **Comentários**
Qualquer dúvida comentar na própria issue.

**Comment by lucaslop** [comment]
Issue concluída  #122
