### ISSUE TITLE
Plano de gestão e configuração de software (GCS)

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#12]
# **Descrição**
Criar documento para definir os procedimentos de gerência e configuração de software para o projeto, como política de commits, issues e outros.

 # **Tópicos do documento**
 - [x] Introdução
 - [x] Políticas
 *  - [x] Política de Commits
 * - [x] Política de Branches
 - [x] Ferramentas
 
# **Comentários**
A equipe irá discutir a respeito das políticas e integração das ferramentas, assim como a adição de novos recursos no documento. Adicionar nos comentários exemplos, caso hajam dúvidas.

**Comment by DanilloGS** [comment]
Aqui está um link com exemplos que serão úteis [Plano GSC](https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/plano-gcs)

**Comment by nicaloribeiro** [comment]
Documento concluído, sujeito a revisões e atualizações conforme decorrer do projeto e necessidades.
