### ISSUE TITLE
Refatoração para links localhost

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#121]
# **Descrição**
Atualmente, algumas rotas sendo elas de compartilhar um questionário, copiar o iframe a de poup da  página ajuda, trabalham sobre o link localhost:3000/ , porém, com o deploy do servidor deve-se pegar o link dinamicamente, já que não estarão mais rodando em localhost. Além disso, deve-se deixar um visual mais agradável, a navbar do Header.ejs 

# **Objetivos**
Pegar o link do servidor dinamicamente, assim funcionará nos 3 servidores e refatoração do Header.ejs

 # **Tasks**

 - [x] os links que funciona localmente (compartilhar formulário,copiar iframe,popup para a página de ajuda) devem funcionar dinamicamente independe do servidor. 
 - [x] Refatoração da partials Header.ejs
# **Comentários**
Qualquer dúvida, comentar abaixo

**Comment by DanilloGS** [comment]
A issue foi resolvida com o PR #124 .
