### ISSUE TITLE
Arquivo .env

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#127]
# **Descrição**
As keys e senhas do mongodb, e do sendgrid estão na aplicação. Assim,comprometendo a segurança da aplicação. Em vista disso, criar um arquivo .env onde ficará as variáveis de ambiente. 

# **Objetivos**
Colocar todas as variáveis de ambiente no arquivo .env

 # **Tasks**

 - [x] Colocar as variáveis de ambiente(username e password) do mongodb no arquivo .env
 - [x] Colocar as variáveis de ambiente(key) do sengrid no arquivo .env
 - [x] Configurar as variáveis de ambiente nos servidores (homologação,produção,acesso público.)
# **Comentários**
Qualquer dúvida comentar abaixo

**Comment by DanilloGS** [comment]
As variáveis de ambiente foram definidas e colocadas em um arquivo .env com sucesso. O PR #132 foi aceito. A issue foi finalizada.
