### ISSUE TITLE
Teste Showdown

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#128]
# **Descrição**
Para a garantia da funcionalidade, deve-se criar um testes unitário do controller showdow.

# **Objetivos**
Deve-se criar um testes unit o controller showdown, com suits de testes necessárias para testar a funcionalidade. Além disso, ter aprovação em todas as suits
# **Tasks**

 - [ ] Teste unitário do controller showdown.js, tendo aprovação em todas as suit

# **Comentários**
Qualquer dúvida/sugestão comentar nessa issue

**Comment by Miguelisdemir** [comment]
O teste não será realizado,pois o código é de outra versão do javascript. Tendo em vista disso, foi realizado apenas testes manuais. Com isso, a corbertura de testes se mantem em 58.29% com 24 testes em 7 suits
