### ISSUE TITLE
Empacotamento Debian

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#129]
# **Descrição**
Deve criar um empacotamento para para a distribuição Debian

# **Objetivos**
Criar um pacote da aplicação Questmark para a distribuição Debian 
 # **Tasks**

 - [x] Empacotar a aplicação para o debian.

# **Comentários**
[Tutorial](https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.pt_BR.pdf) de como empactar para o debian

**Comment by DanilloGS** [comment]
O PR foi realizado e está somente esperando aprovação. Então, a issue atual foi finalizada.
