### ISSUE TITLE
Treinamento GIT e DOCKER

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#13]
# **Descrição**
Realizar treinamento git e docker de forma presencial. Busca por tutores em andamento.

 # **Treinamentos**
 - [x] GIT 
 - [ ] DOCKER
 
# **Comentários**
Comentar na issue dúvidas, caso existam, para providenciar treinamentos eu sanamento das dúvidas.

**Comment by Gustavo-Nogueira** [comment]
Curso gratuito de git: <https://www.udemy.com/course/git-e-github/?xref=two_sided_share>

**Comment by DanilloGS** [comment]
Achei uma [playlist](https://www.youtube.com/playlist?list=PLf-O3X2-mxDkiUH0r_BadgtELJ_qyrFJ_) no youtube sobre Docker que pode ser útil

**Comment by lgpinheiro94** [comment]
Site com alguns comandos básicos de Git comentados e exemplificados para melhor compreensão:
https://www.hostinger.com.br/tutoriais/comandos-basicos-de-git/

**Comment by nicaloribeiro** [comment]
Material sobre [MERN (MongoDb, Express, React e NodeJs) com **Docker**](https://medium.com/codebase/mern-ep01-setting-up-a-development-environment-with-docker-1bb0b6e4d464)

**Comment by Miguelisdemir** [comment]
Feito o treinamento de GitHub na segunda-feira (02/09) com a equipe ADA.

**Comment by nicaloribeiro** [comment]
Não foi possível realizar o treinamento docker presencial.
