### ISSUE TITLE
Desenvolver para apresentação para R2

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#130]
# **Descrição**
Desenvolver uma apresentação em slide que mostre o que foi feito no projeto, a evolução da equipe e do projeto para a R2.

 # **Tasks**
 - [x] Apresentar o produto
 - [x] Mostrar a metodologia de trabalho
 - [x] Funcionalidade prontas
 - [x] Mostrar a cobertura de testes 
 - [x] Futuro do projeto

# **Comentários**
Qualquer dúvida/sugestão,comentar abaixo

**Comment by DanilloGS** [comment]
O slide foi finalizado, então a issue foi completa.
