### ISSUE TITLE
Estudar tecnologias

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#14]
# **Descrição**
Algumas das tecnologias que serão utilizadas foram definidas, é necessário que os membros do grupo realizem tutoriais e estudem materiais relacionados.

 # **As tecnologias definidas foram :**
 - React
 -  MongoDB
 -  JavaScript
 -  NodeJS
- HTML e CSS
- Docker
 
# **Comentários**
Comentem na issue com materiais de estudo, tutoriais e afins , assim como dúvidas que eventualmente possam ser sanadas.

**Comment by nicaloribeiro** [comment]
* [Vídeo aula de API NodeJS + Express + MongoDB](https://www.youtube.com/watch?v=BN_8bCfVp88)

**Comment by lucaslop** [comment]
Acho importante estudar [handlebars](https://handlebarsjs.com/), um template engine, para renderizar páginas html no NodeJS

**Comment by nicaloribeiro** [comment]
[Material](https://medium.com/javascript-in-plain-english/full-stack-mongodb-react-node-js-express-js-in-one-simple-app-6cc8ed6de274) para app fullstack MERN

**Comment by nicaloribeiro** [comment]
* [React do zero](https://blog.rocketseat.com.br/react-do-zero-componentizacao-propriedades-e-estado/) - Esse link leva à primeira de algumas partes sobre React. O post está bem explicado e dá uma boa introdução.
