### ISSUE TITLE
Treinamento de Bootstrap

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [fga-eps-mds/2019.2-Questmark#16]
# **Descrição**
Os membros devem estudar esta tecnologia para desenvolver uma interface estilizada.  Essa tecnologia será utilizada tanto na estilização do site em que será mantido o sistema quanto no momento de fornecer templates de estilização aos usuários para os seus questionários.

# **Tecnologia definida para estilização:**
 - [x] Bootstrap 
 
# **Comentários**
Comentem na issue com materiais de estudo, tutoriais e afins , assim como dúvidas que eventualmente possam ser sanadas.

**Comment by Gustavo-Nogueira** [comment]
Estilização de campos de formulário: <https://getbootstrap.com/docs/4.1/components/forms/>

**Comment by nicaloribeiro** [comment]
[ReactStrap](https://reactstrap.github.io/)  - Bootstrap para componentes
