### ISSUE TITLE
Criar Wiki do Projeto

### ISSUE THREAD

**Issue by Mexazonic** [fga-eps-mds/2019.2-Questmark#17]
# **Descrição**
Os desenvolvedores deverão criar/utilizar a seção para hospedagem de documentação através da Wiki, conforme o padrão da comunidade.
Para a realização desta tarefa é recomendado a seguinte leitura aos participantes:  
<a href="https://help.github.com/en/articles/adding-or-editing-wiki-pages">Adicionando ou Editando Páginas Wiki</a>

 # **Requisitos**
 - [x] Deploy no GitHub Pages
 - [x]  Página acessível a Comunidade

**Comment by DanilloGS** [comment]
Upei no git o inicio da nossa Wiki em [Mkdocs](https://www.mkdocs.org/)

**Comment by nicaloribeiro** [comment]
Github Pages funcionando.
