### ISSUE TITLE
Criar Identidade Visual do Projeto

### ISSUE THREAD

**Issue by Mexazonic** [fga-eps-mds/2019.2-Questmark#19]
# **Objetivos**
Desenvolver a identidade visual do projeto.

 # **Descrição**
A Identidade Visual é o primeiro contado do usuário com a aplicação, ou seja, toda idealização do nome, logotipo, fonte, cor e estilo devem ser considerados como os pilares de sustentação da estratégia de comunicação.  
 # **Tarefas**
- [x] Criar a representação gráfica da Identidade do Projeto 

# **Critérios de aceitação**
 - [x] O logo deve ser reconhecível, simples e objetivo
 - [x] Nitidez

**Comment by lgpinheiro94** [comment]
Toda a identidade visual do projeto foi criada, seguindo os critérios que foram demandados, tendo sido elaborados e definidos, nome, logo, palheta de cores, fontes e demais atributos relacionados a identidade visual
