### ISSUE TITLE
Definir como será implementado as principais funcionalidades do sistema

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [fga-eps-mds/2019.2-Questmark#21]
# **Descrição**
 Os membros devem pesquisar,estudar e validar sugerindo alguma sugestão para as seguintes funcionalidades:
 - Armazenar os questionários criados pelos usuários;
 - Gerar links de compartilhamento de questionário;
 - Armazenar as respostas recebidas referente aos questionários.

 # **Tópicos do documento**
 - [x]  Armazenamento dos questionários.
 - [x]  Links de compartilhamento
 - [x]  Armazenamento das respostas
 
# **Comentários**
Comentem qualquer dúvida que tiverem sobre a issue.

**Comment by nicaloribeiro** [comment]
* Sugestão :
  - Para o armazenamento do questionário : Quando o usuário cria um questionário, é gerado um código HTML. Ao salvar o questionário, será enviado ao banco o ID do criador do questionário e o HTML gerado, sendo possível renderizá-lo em alguma página futura ( [Exemplo básico](http://www.codeexpertz.com/blog/nodejs/nodejs-creating-html-form-post-method) renderizando uma página HTML via GET a partir de strings);
  - Para os links de compartilhamento : [Esta API](https://developers.rebrandly.com/docs) permite a criação de shorts URLs. Então, seria possível passar o link do questionário e disponibilizar a versão encurtada;
  - Para armazenar as respostas : Até o momento não cheguei a algo concreto, apenas que cada resposta terá o ID do seu questionário de origem (Que terá o ID de seu criador) e os dados enviados como respostas serão tratados e exibidos ao usuário;

**Comment by lucaslop** [comment]
- Sugestão : 

- Armazenamento : Com a criação do Questionário, recupera-se no back-end o tipo string. Salva essa string no banco de dados. Na hora de mostrar o questionário para o usuário, renderiza com um template engine ( sugestão: **handlebars**).

- Links de compartilhamento: Para os links, pode-se usar o nome do questionário que o  usuário previamente foi definido. 

- Respostas: As respostas podem ser armazenadas recuperando o id do formulario, e salvam as respostas  em um array de respostas. Ou criar um model de respostas que terá associação com o model formulário.
