### ISSUE TITLE
Estudar integração do WMD 

### ISSUE THREAD

**Issue by Gustavo-Nogueira** [fga-eps-mds/2019.2-Questmark#22]
# **Descrição**
O _WMD: The Wysiwym Markdown Editor_ é um projeto open source que tem como objetivo implementar uma sintaxe que permite criar _inputs,_ como _checkbox,radio,text,_ dessa forma permitindo criar questionários. O projeto também possui suporte para sintaxe padrão do markdown. Além de um _preview_ do resultado gerado pela entrada markdown o projeto oferece também o HTML gerado a partir do markdown que foi passado como entrada.

Utilizaremos,a partir de um fork, esse projeto para fazer o _parse_ da entrada markdown passada pelo usuário. Para tanto é necessário estudar e verificar as formas de utilização dos recursos desse projeto. Mais especificamente descobrir como deve ser feita a integração do WMD no servidor do NodeJS, bem como descobrir como passar um texto em markdown para os métodos que realizam o _parse_ do markdown para HTML e recuperar a saída HTML gerada. 

Link do projeto WMD: The Wysiwym Markdown Editor : <https://github.com/brikis98/wmd>

 # **Tópicos do documento**

-  [x] Integração do WMD no servidor do NodeJS.
 - [x] Envio de texto em markdown para o método de _parse_.
 - [x] Recuperação do HTML gerado.
 
# **Comentários**
Comentem qualquer dúvida que tiverem sobre a issue.

**Comment by lucaslop** [comment]
Com o uso do body-parse, recupera a entrada em markdown e salva como uma string. Para a recuperação pode-se usar um template engine e passar a string que foi recuperada pelo body-parser
