### ISSUE TITLE
WMD

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#37]
# **Descrição**
 Encontrar soluções para incrementar o código do repositório [WMD](https://github.com/brikis98/wmd) de uma forma que melhor atenda melhor as necessidade do projeto

# **Objetivos**
Desenvolver alguma melhoria dentro do código WMD para aceitar o uso de caracteres especias (Exemplo: ç, á, â, ã e etc) para a criação de formulários mais bem elaborados. Além disso, deve-se estudar formas de adicionar campos obrigatórios para todos os tipos de opções (Radio, Select,Checkbox).

 # **Tasks**
 'Adicionar o que deve ser feito na issue'
- [x]  Subir wmd no git;
- [x] Formas de resolver o problema de caracteres especiais;
- [x] Estudar formas de incluir campos obrigatórios (Radio, Select,Checkbox)
- [ ] Implementar campos obrigatórios (Opcional)

**Comment by Gustavo-Nogueira** [comment]
Links para estudo das expressões regulares no javascript: 
Introdução: <https://www.youtube.com/watch?v=9r48XuOB4DA>
Documentação: <https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_Expressions>

**Comment by DanilloGS** [comment]
Tive que criar uma nova pasta do WMD, pois tinha esquecido de apagar o arquivo .git da pasta WMD original

**Comment by DanilloGS** [comment]
O erro de caracteres especiais foi consertado com a utilização de expressões regulares

**Comment by DanilloGS** [comment]
Para adicionar campos de respostas obrigatórios em todas as opções de respostas é mais complexo do que o esperado. Mudanças intrínsecas no funcionamento do código WMD teriam que ser realizadas.

**Comment by DanilloGS** [comment]
Uma solução é a própria equipe do projeto Questmark implementar essa funcionalidade para adicionar no repositório
