### ISSUE TITLE
Refatorar o layout 

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#48]
# **Descrição**
Refatorar o layout de views existentes em EJS para ReactJs

**Comment by nicaloribeiro** [comment]
* Tasks
- [x] Página de listar formulários;
- [x] Página de criar formulários;

**Comment by DanilloGS** [comment]
Refatorar a página WMD poderá ser um pouco penoso. Se houver problemas para integrar o React com o Backend, poderemos usar essa dica que encontrei no [stackoverflow](https://stackoverflow.com/questions/33973757/how-can-i-render-html-from-another-file-in-a-react-component)

**Comment by nicaloribeiro** [comment]
* Layout da página de criar formulários concluído, porém houve dificuldades para inserir o WMD no react. Foi decidido que essa integração (React + WMD) será feita posteriormente em uma issue específica, visto que aparentemente não é tão simples quanto pensado;
