### ISSUE TITLE
Adicionar Nodemon no projeto

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#51]
# **Descrição**

Adicionar a ferramenta para desenvolvimento Nodemon no projeto

# Objetivos

Automatizar o processo de atualização do código para que não precise ficar reiniciando a aplicação a cada alteração

# Tasks

- [x] Instalar o nodemon

- [x] Configurar juntamente com o Docker

**Comment by lucaslop** [comment]
Concluída!
