### ISSUE TITLE
Criptografia

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#53]
# **Descrição**
Criptografar senhas de usuários da plataforma

# **Comentários**
Link que pode ser útil: http://www.passportjs.org/

**Comment by Gustavo-Nogueira** [comment]
Foi utilizado o algoritmo de hash MD5 para gerar uma hash de 32 bytes para as senhas dos usuários. Para tanto, foi utilizado módulo Crypto.
