### ISSUE TITLE
Introdução à documentação

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#6]
* É de grande importância que os membros do grupo possuam ao menos uma visão geral a respeito do Documento de Visão e Documento de Arquitetura.

* [Documento de visão - IBM introdução e exemplo](https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html)

* [Documento de arquitetura - Introdução](http://www.linhadecodigo.com.br/artigo/3343/como-documentar-a-arquitetura-de-software.aspx)

* [Documento de arquitetura - exemplo](http://mds.cultura.gov.br/extend.formal_resources/guidances/examples/resources/sadoc_v1.htm)

**Comment by DanilloGS** [comment]
#### Documentação na Wiki:
Aqui são dois projetos, de amigos meus, que foram bem avaliados por conta da organização da documentação.
- [Wiki do ADA](https://fga-eps-mds.github.io/2019.1-ADA/)
- [Repositório do ADA](https://github.com/fga-eps-mds/2019.1-ADA)
- [Wiki IndicaAí](https://fga-eps-mds.github.io/2018.2-IndicaAi/)
- [Repositório IndicaAí](https://github.com/fga-eps-mds/2018.2-IndicaAi)
- [Repositorio FisicAE](https://github.com/fga-eps-mds/fisCAE-2017-2/wiki)
