### ISSUE TITLE
Iniciar estudos do Chart.js

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#60]
# **Descrição**
- Chart.JS é uma biblioteca baseada JavaScript que possibilita a criação de gráficos animados em uma página HTML.
 
# **Objetivos**
- A biblioteca será usada, futuramente, para desenvolvermos nosso Dashboard, indispensável para o projeto. A biblioteca também permite que esses gráficos sejam salvos em formato de imagem.

# **Comentários**
- [Básico da biblioteca (Inglês)](https://www.youtube.com/watch?v=sE08f4iuOhA)
- [Básico da biblioteca (Portugês)](https://www.youtube.com/watch?v=l0K95at8BVg)
- [Solução no Stackoverflow para converter Chart.JS em imagem](https://stackoverflow.com/questions/43664722/how-to-save-chart-js-charts-as-image-without-black-background-using-blobs-and-fi)

**Comment by nicaloribeiro** [comment]
O **ChartJS** possui uma [DOCUMENTAÇÃO](https://www.chartjs.org/docs/latest/getting-started/) interessante, mas vou deixar o link de algumas opções de bibliotecas que, ao meu ver, também possuem uma boa documentação :
* [Apex Charts](https://apexcharts.com/docs/installation/)
* [Google Charts](https://developers.google.com/chart/interactive/docs/quick_start)
* [EJS Chart](http://www.ejschart.com/index.php)
