### ISSUE TITLE
Criar um diagrama de arquitetura

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#63]
# **Descrição**
Após o Feedback da professora Carla um novo diagrama de arquitetura terá que ser desenvolvido.

# **Objetivos**
Criar um diagrama de arquitetura com todas as interações possíveis que o projeto possui, o diagrama anterior apresentado na Release 1 foi desenvolvido de maneira equivocada/totalmente genérico.

 # **Tasks**
 - [x] Deve conter todas as interações possíveis do projeto.
 - [x] Deve conter todas as tecnologias que estão sendo usadas para o desenvolvimento do projeto.
 - [x] As relações de uma tecnologia com a outra deve ser mostradas de forma explicita.

# **Comentários**
Qualquer duvida comente na própria issue

**Comment by Gustavo-Nogueira** [comment]
Primeira versão do diagrama de arquitetura elaborado por @lgpinheiro94 e @Gustavo-Nogueira:
![diagrama-v1](https://user-images.githubusercontent.com/36088551/66710328-5de38500-ed4c-11e9-813c-16c341545d26.png)

**Comment by Gustavo-Nogueira** [comment]
Segunda versão do diagrama de arquitetura elaborado por @lgpinheiro94 e @Gustavo-Nogueira:
![diagrama-v3](https://user-images.githubusercontent.com/36088551/66717762-1cd28b80-edb3-11e9-80a8-90a713f19d4c.png)

**Comment by DanilloGS** [comment]
A issue foi finalizada com sucesso após a apresentação de um diagrama de arquitetura menos genérico
