### ISSUE TITLE
Finalizar a autenticação

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#64]
# **Descrição**
Para a autenticação de um usuário, é preciso verificar se o hash (senha criptografada) que foi inserido no login é igual ao que foi cadastrada e posteriormente salva  no banco de dados. Além disso, é necessário, proteger a rota de criar um novo formulário. Para que, usuários não logados no sistema, não tenham acesso a essas rotas.

# **Objetivos**

Comparar a senha do usuário, com o hash que foi cadastro no banco de dados previamente. Além disso, somente usuários logados no sistema, deve criar formulários. Com isso, asseguraremos a segurança do usuário e do sistema.  

 # **Tasks**

 - [x] Deve autenticar um usuário se e somente se, a senha digitada no login, for igual à cadastrada  previamente.
 - [x] Somente usuários logados no sistema deve ter acesso as rotas de criar formulário e listar formulários
 - [x] Usuários não logados no sistema, ao tentar acessar as rotas de criar formulário e listar formulários, devem ser redirecionados para a rota login

# **Comentários**
Qualquer duvida sobre a issue comentar abaixo, isso inclui sugestão de arquivos que já não estão mais sendo utilizados.

**Comment by Gustavo-Nogueira** [comment]
A branch 64-finalizar-autenticação foi criada para o concluir o desenvolvimento dessa feature.

**Comment by DanilloGS** [comment]
A issue foi concluída e recebeu um merge. O PR que resolve essa issue é o [#70]
