### ISSUE TITLE
Logout de usuário 

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#65]
# **Descrição**
Quando um usuário concluir seu objetivo na plataforma, deve sair do sistema para que seus dados não fiquem vulneráveis.  
# **Objetivos**

O Logout irá garantir ao usuário que ninguém tenha acesso à sua conta através do dispositivo que foi efeituado o login. 

 # **Tasks**

 - [x] Deve retirar o usuário do sistema 
 - [x] Deve redirecionar após o logout, para a rota login

# **Comentários**
Qualquer duvida sobre a issue comentar abaixo, isso inclui sugestão de arquivos que já não estão mais sendo utilizados.

**Comment by nicaloribeiro** [comment]
* [Documentação](http://www.passportjs.org/docs/logout/) do PassportJS à respeito do logout.
@DanilloGS dê uma olhada.

**Comment by DanilloGS** [comment]
@lucaslop em qual arquivo deve ocorrer essa mudança?

**Comment by lucaslop** [comment]
@DanilloGS No arquivo users cria a rota de logout, para quando o usuário clicar no botão de logout, ser redirecionado para lá. Dentro da rota, é so colocar req.logout que é uma função do passport

**Comment by DanilloGS** [comment]
Ambas as tasks foram finalizadas, o PR já foi solicitado. Aguardando o merge para a develop
