### ISSUE TITLE
Criar o front-end da rota home

### ISSUE THREAD

**Issue by lucaslop** [fga-eps-mds/2019.2-Questmark#66]
# **Descrição**
Para a experiencia de usuário, o layout deve-ser de fácil utilização, visualmente agradável e funcional. 

# **Objetivos**

Ao acessar a rota home, deve renderizar ao usuário, um layout principal, contendo informações principais acerca do produto. De fácil manuseio por parte do usuário  

 # **Tasks**

 - [x] Deve proporcionar ao usuário, uma experiencia agradável ao acessar a pagina    
 - [x] Deve conter as principais informações do projeto resumidamente em cards
 - [x] Deve ter os botões para as rotas de login, cadastro e ajuda

# **Comentários**
Qualquer duvida sobre a issue comentar abaixo, isso inclui sugestão de arquivos que já não estão mais sendo utilizados.

**Comment by lucaslop** [comment]
Aqui pode ser encontrado [Ícones](https://icons8.com.br/icons), sem direitos autorais para usar no front-end. É exigido que  coloque um link se caso for usado um ícone desse site, por causa do Creative Commons Attribution-NoDerivs 3.0 Unported.

**Comment by lucaslop** [comment]
@DanilloGS @lgpinheiro94  Qual fonte foi usada para a logo?

**Comment by DanilloGS** [comment]
@lucaslop a fonte que estamos usando para a logo é a [Knewave](https://fonts.google.com/specimen/Knewave?selection.family=Knewave)
