### ISSUE TITLE
Concluir páginas de login, cadastro e ajuda

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#68]
# **Descrição**
Concluir páginas de login, cadastro e ajuda em HTML. Houveram problemas na última sprint que impossibilitaram a utilização do ReactJS no desenvolver do projeto.

# **Objetivos**
Criação de páginas fundamentais para o desenvolvimento do projeto. 

 # **Tasks**
 - [x] Página de Login
 - [x] Página de cadastro de usuários novos
 - [x] Página de ajuda e dúvidas  

# **Comentários**
Qualquer dúvida de como realizar cada página comente na própria issue.

**Comment by nicaloribeiro** [comment]
* Foi decidido, em conluio com o @DanilloGS , que a página de Ajuda terá seu design e conteúdo revistos, uma vez que ela será uma página à parte do que está previsto no protótipo de alta fidelidade.
