### ISSUE TITLE
Rever layout das páginas e deixá-las responsivas

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#76]
# **Descrição**
Um site responsivo é aquele cuja disposição dos elementos e o conteúdo se adaptam de acordo com o tamanho da tela do usuário. Isso permite ao usuário encontrar de maneira fácil o que deseja, sempre com uma navegação simples e intuitiva.
# **Objetivos**
Para essa *issue*, é necessário rever as páginas já criadas e refatorar o layout (caso seja necessário) e torná-las responsivas para elevar a experiência de usuário. Essa issue também será destinada para criação de _pop-ups_ que facilitarão a interação do usuário com a plataforma.

 # **Tasks**
 * - [x] Refatorar e tornar responsiva as páginas relacionadas a **FORMULÁRIOS**;
 * - [x] Cadastro de formulários;
 * - [x] Início;
 * - [x] Lista de respostas;
 * - [x] Visualizar formulários ;
 * - [x] _Pop-up_ para a opção de **AJUDA**;
 * - [x] _Pop-up_ de confirmação ao tentar apagar questionários;
 * - [x] _Pop-up_ de sucesso e falha para o cadastro de questionários;

# **Comentários**
Por envolver muitas páginas, caso seja necessário solicitar ajuda, opiniões sobre o layout e outras coisas que podem surgir eventualmente, comentar na *issue*.

**Comment by lucaslop** [comment]
A issue foi realocada para a sprint 9. Com a divida técnica da página de ajuda

**Comment by DanilloGS** [comment]
Um link que será útil para criação de uma página de ajuda com [overlay](https://www.w3schools.com/howto/howto_css_overlay.asp)

**Comment by Gustavo-Nogueira** [comment]
As tasks da issue foi atualizada para inserir os _pop-ups_ que a plataforma deve possuir.

**Comment by Gustavo-Nogueira** [comment]
Segue uma boa referência para a criação de _pop-ups_ a partir do _bootstrap_:
<https://getbootstrap.com.br/docs/4.1/components/modal/>
