### ISSUE TITLE
Criar página do Dashboard

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#78]
# **Descrição**
Desenvolver uma página de Dashboard que irá renderizar gráficos de acordo com as respostas obtidas no questionário, usando os conhecimentos obtidos na Issue #60.

# **Objetivos**
Criar um Backend (Utilizando chartJS ou outras tecnologias recomendadas) e Frontend e integra-los.

 # **Tasks**
 ## Backend
 - [x] Criar rota para o dashboard
 - [x] Receber as respostas do usuário
 - [x] Tratar as resposta do usuário

## Frontend
 - [ ] Criar uma página responsiva
 - [ ] Criar uma página com design agradável ao usuário
 - [ ] Usar as respostas tratadas para renderizar os gráficos  

# **Comentários**
Qualquer discussão relacionada a Issue comentar abaixo

**Comment by nicaloribeiro** [comment]
Para melhor organização e planejamento para resolver a issue, irei dividi-la em duas : uma para o front-end e outra para o back-end.

**Comment by Gustavo-Nogueira** [comment]
Entendido.
