### ISSUE TITLE
Converter JSON para CSV

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#80]
# **Descrição**
 Converter o formato de dados JSON para CSV para que o usuário possa usufruir ao máximo das respostas dadas ao seu questionário. (Sugerido pela professora Carla)

# **Objetivos**
O usuário tem que ter o poder de converter os seu dados obtidos na pesquisa e fazer o download do mesmo já em CSV sempre que for solicitado.

 # **Tasks**
 - [x] Converter JSON para CSV
 - [x] Adicionar uma rota para a conversão
 - [x] Fazer download do CSV  

# **Comentários**
Qualquer discussão relacionada a Issue comentar abaixo

**Comment by DanilloGS** [comment]
Ainda estou tentando diversas formas de fazer o dowload do CSV, a mais provável é uma rota especifica para download

**Comment by lucaslop** [comment]
> Ainda estou tentando diversas formas de fazer o dowload do CSV, a mais provável é uma rota especifica para download

A solução encontrada foi usar o Buffer

**Comment by DanilloGS** [comment]
O PR #88 foi aceito, concluindo então a presente issue.
