### ISSUE TITLE
(BUG) Correção de bugs na criação de questionários

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#86]
# **Descrição**
## Bug 1
- Consertar bugs de quebra de linha na hora de cadastrar/visualizar questionário
1- Assim não funciona corretamente:
```
Nome = __
Sexo = ()M ()F
```
 2- Assim funciona corretamente:
```
Nome = __

Sexo = ()M ()F
```
---
## Bug 2
- Consertar bugs de entrada de resposta quando os dois campos possuem o mesmo nome 
```
Radio = ()1 ()2 ()3
Checkbox = []1 []2 []3
```
---
## Bug 3
- Caixa de texto da _view_ editar_formulario possui uma quebra de linha pré-inserida. É necessário remover essa quebra de linha para que o _markdown_  do formulário a ser editado não fique desformatado.
---
# **Objetivos**
Corrigir os bugs gerados pela pré-formatação de saída _markdown_ e HTML fornecidas pelo código do projeto WMD. Acredita-se que os dois primeiros bugs serão corrigidos da mesma forma.

 # **Tasks**
 - [x] Bug 1
 - [x] Bug 2
 - [x] Bug 3

# **Comentários**
Qualquer discussão sobre a issue comentar abaixo.

**Comment by Gustavo-Nogueira** [comment]
Serão realizadas pequenas modificações no código no arquivo _[showdown.js](https://github.com/fga-eps-mds/2019.2-Questmark/blob/develop/frontend/public/wmd/showdown.js)_ do wmd para corrigir o _bug 1_ indicado nas descrição da issue.

**Comment by Gustavo-Nogueira** [comment]
O _bug 2_ é uma restrição do próprio html, ou seja, não é  possível criar _inputs checkbox_ e _inputs radio_ com as opções de seleção dos campos possuindo o mesmo nome nas _labels_.
