### ISSUE TITLE
Estudo de como implementar iframe

### ISSUE THREAD

**Issue by DanilloGS** [fga-eps-mds/2019.2-Questmark#87]
# **Descrição**
Estudar como funciona a implementação do iframe e usa-lo na plataforma, como foi sugerido pela professora Carla. 

# **Objetivos**
Estudar iframe para implementa-lo já na próxima sprint. Criem protótipos básicos para uma maior aprendizagem. 

# **Comentários**
Link que será útil: [Criar um iFrame](https://www.youtube.com/watch?v=WRcs8rebZtA)

**Comment by nicaloribeiro** [comment]
Alguns links interessantes :
* [Guia sobre iframe](https://www.hostinger.com.br/tutoriais/o-que-e-iframe/)
* [Outro guia sobre iframe](https://www.homehost.com.br/blog/tutoriais/iframe-html/)
* [Discussão](https://pt.stackoverflow.com/questions/29841/por-que-o-uso-de-frames-e-iframes-%C3%A9-considerado-uma-m%C3%A1-pr%C3%A1tica) interessante no StackOverflow a respeito de iframes
