### ISSUE TITLE
Criar front-end do Dashboard ( #78 )

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#89]
# **Descrição**
A *issue* #78 foi dividida em duas para melhor organização e execução. Esta parte, especificamente, trata-se do front-end.

# **Objetivos**
Criar o front-end para a página do dashboard e integrá-la com o back-end.

 # **Tasks**
 - [ ] Criar página com layout agradável para o usuário 
 - [x] Utilizar alguma das bibliotecas sugeridas na issue #60 
 - [x] Integrar com o back-end

**Comment by nicaloribeiro** [comment]
Eu e o @Miguelisdemir estamos com algumas dificuldades para trabalhar com os dados no front-end.
A situação é a seguinte : 
* Quando se clica no Ícone da dashboard o usuário é redirecionado para a página referente;
* É passado como "parâmetro" da página EJS as respostas dos formulários, os tipos dos inputs e quais são (radio, select...) e os nomes das variáveis que foram destinadas para cada input;

Para gerar os gráficos (utilizando alguma das bibliotecas citadas na issue #60) seria necessário separar cada input e suas respectivas respostas, só que estamos tendo algumas dificuldades nisso. Se alguém puder ajudar seria interessante, especialmente alguém que tenha mais conhecimento no EJS. Ou propor alguma solução, trabalhar os dados no backend talvez (não sei se é viável fazer isso, em questão de desempenho principalmente).
Outro ponto interessante seria definir quais tipos de gráficos utilizar, visto que cada gráfico tem uma aplicação específica e depende muito da situação( [Aqui](https://4.bp.blogspot.com/-qiQHGkZAEeA/UyxHACBGmbI/AAAAAAAAEyg/zaytO9fUR9Q/s1600/qual_grafico_usar.jpg) uma imagem que demonstra o processo de escolha do gráfico e [Aqui](https://www.dadosfinos.info/2014/03/que-tipo-de-grafico-usar.html) a matéria completa). 
Mas enfim, aguardo respostas, seja com ajuda, ideias ou soluções, qualquer coisa é bem-vinda.
@DanilloGS @Gustavo-Nogueira @lucaslop @lgpinheiro94

**Comment by Gustavo-Nogueira** [comment]
Entendido. Tentarei ajudar da melhor forma possível.

**Comment by lucaslop** [comment]
A issue foi realocada como divida técnica para a sprint 9. Uma nova dupla foi designada para essa sprint. o @Gustavo-Nogueira  e o @lgpinheiro94

**Comment by lgpinheiro94** [comment]
Transferido para a Sprint 9

**Comment by Miguelisdemir** [comment]
Está sendo implementado, um código que gera um histograma, a partir das respostas enviadas pelo back-end, então a partir desse histograma poderá ser gerado os gráficos.

**Comment by Gustavo-Nogueira** [comment]
@nicaloribeiro @Miguelisdemir @lucaslop @DanilloGS verifiquem se layout da página de dashboard está conforme o desejado, por favor.
