### ISSUE TITLE
Definir identidade visual inicial do projeto

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#9]
# **Descrição**
Definir , a identidade visual inicial do projeto, para que todos os membros do grupo estejam cientes e ajudarem a definir a identidade visual completa.

 # **Tasks**
 - [x] Criar protótipo de baixa fidelidade
 - [x] Definir nome do produto

**Comment by DanilloGS** [comment]
O nome do projeto foi definido e o protótipo de baixa fidelidade do projeto foi elaborado por @Gustavo-Nogueira.
