### ISSUE TITLE
Criar back-end do Dashboard ( #78 )

### ISSUE THREAD

**Issue by nicaloribeiro** [fga-eps-mds/2019.2-Questmark#90]
# **Descrição**
A *issue* #78 foi dividida em duas para melhor organização e execução. Esta parte, especificamente, trata-se do back-end.

# **Objetivos**
Criar as rotas que disponibilizarão os dados a serem usados no front-end para visualização intuitiva do usuário.

 # **Tasks**
 - [x] Criar rota
 - [x] Tratar os dados que serão passados pela rota
 - [x] Disponibilizar a rota para uso do front-end

**Comment by Gustavo-Nogueira** [comment]
Pessoal, os campos já foram mapeados, dessa forma basta acessar o atributo _type_inputs_ do objeto formulário que vocês terão acesso a todos os campos de cada formulário. Isso vai facilitar na hora de gerar _dashboard_, pois basta pegar somente os campos que possuem opção de seleção(_checkbox_,_radio_ e _select_) para gerar o _dashboard_.

**Sugestão:**
Preparar um _json_ no _backend_  contendo o nome dos campos e para cada opção a frequência de respostas recebidas. 

**Exemplo:**  
Supondo um campo _radio_ para seleção fruta preferida.

Markdown WMD:
Fruta = ()Maçã ()Laranja ()Morango

_JSON_ para o _dashboard:_
fruta{maçã: 10,laranja: 25,morango: 15}

Qualquer dúvida é só deixar nos cometários, ok?

**Comment by nicaloribeiro** [comment]
Os nomes dos campos estão sendo enviados separadamente das respostas. A princípio, a frequência das respostas serão tratadas já no front-end junto aos gráficos.
