### ISSUE TITLE
Configuração da funcionalidade de recuperação de senha

### ISSUE THREAD

**Issue by lgpinheiro94** [fga-eps-mds/2019.2-Questmark#94]
# **Descrição**
Criação e configuração de um Host SMPT para o envio de e-mail de recuperação de senha do usuário. Criar um frontend para que o usuário tenha o acesso ao formulário de solicitação de recuperação de senha, tal formulário deve conter o campo e-mail e as devidas instruções para que o usuário consiga prosseguir com a recuperação de senha. Criar um segundo frontend para recuperação de senha do usuário de forma que esse frontend contenha um formulário, que possua um campo de nova senha e confirmação de nova senha e um opção de submissão dos dados.

# **Objetivos**
Essa issue objetiva a criação de um Host para enviar e-mail para os usuários com a finalidade de enviar um token de recuperação de senha, trabalhando com SMPT para realizar a tarefa. Nessa issue também deve conter a criação de duas telas para que o usuário consiga recuperar a sua senha de forma segura, para tanto o usuário após a solicitação de recuperação de senha, poderá entrar no seu e-mail e acessar o link gerado no backend, assim acessando a página de recuperação de senha.

 # **Tasks**
 - [x] Criar o frontend de solicitação;
 - [x] Criar o frontend de definição de nova senha;
 - [x] Validação dos campos de entrada;
 - [x] Integrar com o backend;
 - [x] Configuração do Host SMPT;
 - [x] Deve salvar a nova senha criptografada no banco de dados

# **Comentários**
Dúvidas e sugestões, por parte dos envolvidos na issue o restante da equipe, também devem ser comentadas na issue.

**Comment by nicaloribeiro** [comment]
Opções que estão sendo analisadas para o envio de email :
* [Mail Chimp](https://www.mailchimp.com/)
* [SendGrid](https://sendgrid.com/) -- [Pacote](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail) para Node
* [Mandrill](https://mandrill.com/)
* [Sparkpost](https://www.sparkpost.com/)

**Comment by nicaloribeiro** [comment]
* Dentre as opções para o envio de e-mail, foi escolhido o Sendgrid.

**Comment by nicaloribeiro** [comment]
A key da api para envio de email será retirada do código momentaneamente por motivos de segurança e pelo fato de que há um limite para envios de e-mail. Os demais membros serão instruídos a conseguirem uma nova key para testes e, próximo à R2, a key estará disponível para uso.
