### ISSUE TITLE
Estudo de empacotamento em Debian X

### ISSUE THREAD

**Issue by lgpinheiro94** [fga-eps-mds/2019.2-Questmark#95]
# **Descrição**
Estudar sobre empacotamento em Debian e averiguar as possibilidades de aplicação no projeto Questmark.

# **Objetivos**
Essa issue tem como objetivo o estudo sobre o processo de empacotamento em Debian e verificação de uma possível aplicação disso no projeto Questmark.

# **Comentários**
Dúvidas e sugestões, por parte dos envolvidos na issue o restante da equipe, também devem ser comentadas na issue.

**Comment by lgpinheiro94** [comment]
https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.pt_BR.pdf galera encontrei esse link aqui com um manual de empacotamento Debian que é bastante recente, consta de 13/03/2019, creio que será bastante útil para o nosso projeto, acho interessante todos darem uma olhada no manual.

**Comment by lucaslop** [comment]
[Videos](https://www.youtube.com/watch?v=RJMN-EPijFM&list=PLIFOx3X8xDutD705-J-l-RGUnaLtup-l9) ensinando como empacotar para o debian
