### ISSUE TITLE
Implementação de feature que gera o Iframe

### ISSUE THREAD

**Issue by lgpinheiro94** [fga-eps-mds/2019.2-Questmark#97]
# **Descrição**
 Implementar funcionalidade que permite que o usuário consiga fazer o _embeded_ dos seus formulários em outras páginas.

# **Objetivos**
Essa issue tem como objetivo a implementação da feature que gera o Iframe, para que o usuário consiga incorporar os seus formulários em outras páginas, para tanto deve ser provido duas formas de disponibilização dessa feature (link ou iFrame).

 # **Tasks**
* - [x] Implementar iFrame;
* - [x] _Pop-up_ de compartilhamento de questionário. Nele o usuário poderá escolher entre o link(onde é possível ter acesso ao questionário e submeter respostas) ou iFrame(utilizado para fazer o _embeded_).
* - [x] Testar com ngrok.

# **Comentários**
Dúvidas e sugestões, por parte dos envolvidos na issue o restante da equipe, também devem ser comentadas na issue.

**Comment by lucaslop** [comment]
Link para o [Download](https://ngrok.com/download) do ngrok. Após a instalação, executar com o seguinte comando ./ngrok http (porta desejada).

exemplo: ./ngrok http 5000

**Comment by Gustavo-Nogueira** [comment]
Segue uma boa referência para a criação de pop-ups a partir do bootstrap:
https://getbootstrap.com.br/docs/4.1/components/modal/

**Comment by DanilloGS** [comment]
Apesar de ser uma tarefa marcada como backend, ela foi desenvolvida no frontend sem problema algum e de uma forma mais simples. Ou seja, não houve a necessidade da criação de uma nova rota.

**Comment by DanilloGS** [comment]
A issue foi solucionada. Foi adicionado a opção de copiar um iFrame para implementar diretamente em uma página HTML qualquer. O Pull request foi feito e os conflitos com a develop já foram solucionados.
